# Generated by Django 5.0.6 on 2024-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seguidores', models.PositiveIntegerField()),
                ('edad', models.PositiveBigIntegerField()),
                ('departamento', models.CharField(max_length=100)),
                ('meGusta', models.PositiveBigIntegerField()),
            ],
        ),
    ]
