# Generated by Django 5.0.6 on 2024-06-02 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRedSocia', models.CharField(max_length=100)),
                ('seguidores', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='estadistica',
            old_name='Seguidores',
            new_name='seguidores',
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCampania', models.CharField(max_length=100)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('fechaFinal', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('presupuesto', models.PositiveIntegerField()),
                ('estadistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Marketing.estadistica')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=100)),
                ('fechaRealizacion', models.DateTimeField(auto_now_add=True)),
                ('musica', models.CharField(max_length=100)),
                ('cominda', models.CharField(max_length=100)),
                ('actividadRecreativa', models.CharField(max_length=100)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Marketing.campania')),
            ],
        ),
        migrations.AddField(
            model_name='estadistica',
            name='redSocial',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_Marketing.redessociales'),
            preserve_default=False,
        ),
    ]
