# Generated by Django 5.0.6 on 2024-06-03 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Marketing', '0002_redessociales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='redSocial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Marketing.redessociales'),
        ),
    ]
