# Generated by Django 5.0.6 on 2024-06-03 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Marketing', '0003_alter_estadistica_redsocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campania',
            name='estadistica',
        ),
        migrations.AddField(
            model_name='estadistica',
            name='campania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_Marketing.campania'),
            preserve_default=False,
        ),
    ]
