# Generated by Django 5.0.6 on 2024-06-03 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Marketing', '0004_remove_campania_estadistica_estadistica_campania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='campania',
        ),
        migrations.AddField(
            model_name='campania',
            name='campania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_Marketing.evento'),
            preserve_default=False,
        ),
    ]
