# Generated by Django 5.0.6 on 2024-06-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Marketing', '0005_remove_evento_campania_campania_campania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fechaRealizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
